export const CREATE_OR_UPDATE_REWARD = "CREATE_OR_UPDATE_REWARD";
export const GET_REWARDS_SUCCESS = "GET_REWARDS_SUCCESS";
export const GET_REWARDS_FAIL = "GET_REWARDS_FAIL";
export const CREATE_OR_UPDATE_REWARD_FAIL = "CREATE_OR_UPDATE_REWARD_FAIL";

export const REWARD_STATS_TODAY_REQUEST = "REWARD_STATS_TODAY_REQUEST";
export const REWARD_STATS_TODAY_SUCCESS = "REWARD_STATS_TODAY_SUCCESS";
export const REWARD_STATS_TODAY_FAIL = "REWARD_STATS_TODAY_FAIL";
