export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_UPDATE_SPINS_REQUEST = "USER_UPDATE_SPINS_REQUEST";
export const USER_UPDATE_SPINS_SUCCESS = "USER_UPDATE_SPINS_SUCCESS";
export const USER_UPDATE_SPINS_FAIL = "USER_UPDATE_SPINS_FAIL";
export const USER_UPDATE_SPINS_RESET = "USER_UPDATE_SPINS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";

export const RESET_FREE_SPINS_REQUEST = "RESET_FREE_SPINS_REQUEST";
export const RESET_FREE_SPINS_FAIL = "RESET_FREE_SPINS_FAIL";
export const RESET_FREE_SPINS_SUCCESS = "RESET_FREE_SPINS_SUCCESS";

export const USER_CONNECTION_STATUS = "USER_CONNECTION_STATUS";
